### ISSUE TITLE
Provide custom chepy.conf location

### ISSUE THREAD

**Issue by geekscrapy** [securisec/chepy#7]
I'd like to be able to provide a custom location for the plugins. It would be great if we could provide a custom location for the chepy.conf location too. In addition, I think it would be an idea to search the current location for chepy.conf, both the users cwd and the .py file

**Comment by securisec** [comment]
@geekscrapy You can provide a custom location for the plugins already. Just specify your custom location in `pluginpath` in the chepy.conf file. By default, it will try to use its own plugins which are packed with the latest repos. You can see those [here](https://github.com/securisec/chepy_plugins). If you place your own plugins in that folder, Chepy will load them. If not, and you specific your own directory, then it will load only what it finds in that directory.

As for the location of the conf file itself, because there are various ways of installing chepy, it is not a super good idea to have it look in the current location. If someone uses pip to install chepy, then the current location becomes the site-packets/chepy dir which becomes cumbersome for the user to update. As for use cases of a cwd location for the conf file, it does assume that the user will set a valid conf file, which the average user might fail too. So having a standard good known config file and location follows the pattern of most popular tools out there. 

Thanks for the issues.

**Comment by geekscrapy** [comment]
The issue I have with not having the cwd as a valid conf is this; chepy is part of my tool, I distribute my tool and I need to be able to set the plug-in directory to a directory in my tools "plugin" dir. This way I can distribute my own plugins with my own tool. Without this I have to get people to manually mod the chepy conf (which they shouldn't have to do, as chepy is only used in my tool internally, therefore people wont know to even change the plugin path!). If it's a library it needs to be portable, without the end user having to customise their setup for a lib, which is part of the bigger tool. I will say, there are also lots of other tools that will look in the following places to find the conf (usually in this order):
$cwd
$home
/etc
 Hope that makes sense! 😅

**Comment by securisec** [comment]
Ah, i understand your use case. I will consider building that out. As an alternative, if you are distributing it as a tool, you can modify [this line](https://github.com/securisec/chepy/blob/master/chepy/config.py#L13). Set `home = Path().resolve()`. 

Hope this solution helps in the meanwhile till next release!

**Comment by geekscrapy** [comment]
So you know, I'm currently doing this to get round the limitation:
```
from pathlib import Path
bin_path = os.path.dirname(os.path.realpath(__file__))
def custom_Chepy():
    import chepy
    conf = chepy.ChepyConfig()
    conf.plugin_path = Path(os.path.join(bin_path,'plugins'))
    _plugins = conf.load_plugins()
    class Chepy(
        chepy.AritmeticLogic,
        chepy.CodeTidy,
        chepy.Compression,
        chepy.DataFormat,
        chepy.DateTime,
        chepy.EncryptionEncoding,
        chepy.Extractors,
        chepy.Forensics,
        chepy.Hashing,
        chepy.Language,
        chepy.Multimedia,
        chepy.Networking,
        chepy.Other,
        chepy.Publickey,
        chepy.Search,
        chepy.Utils,
        *_plugins
    ):
        pass

    return Chepy
```

**Comment by securisec** [comment]
Interesting approach. The way I suggested with pathlib didn't work?

**Comment by securisec** [comment]
Ah glad you have it working. Not sure why my suggested method didn't work, but happy it is working for you now. I am still keeping it in mind your feature request for next version. Out of curiosity, what kind of plugins are you developing for chepy? I am always very open to ideas that can enhance chepy itself.

**Comment by geekscrapy** [comment]
It would be file based plugins - renaming files, moving etc. Things that you can't normally do with a browser. So I'd be looking for more of those types of plugins in the future. FYI, the main reason I was looking at using chepy over the CyberChefAPI in node was because node takes a while to load it's imports, which is a killer for cli tool...

To be honest, I didn't try your method as it would mean I have to modify chepy code where-ever I want to run my tool, so it wasn't really an option.

**Comment by securisec** [comment]
@geekscrapy I just release version 2.1.3 which implements your requested feature. It will not look at $CWD for a `.chepy` folder where the configs are. You can refer to [docs](https://chepy.readthedocs.io/en/latest/config.html) for more config objects. So if you distribute your package with a `.chepy` folder, then you can specify your own chepy.conf file with the proper keys to enable and set plugin paths. If you just supply an empty `.chepy` dir in cwd, then it will create the default conf files at first run.

**Comment by geekscrapy** [comment]
Just an FYI, even though the .chepy dir is loaded from the CWD, the plugin_path is still required to be absolute which means the original issue exists.
